### ISSUE TITLE
Having an issue with this

### ISSUE THREAD

**Issue by NerijusD** [xMlex/l2walker#2]
`ant dist`
`cd build`
`java -jar l2walker.jar`

Getting an error:
`Error: Could not find or load main class fw.gui.MainAppForm`

What's the issue?

**Comment by xMlex** [comment]
@NerijusD  Hi!

after `ant dist` run 
`cd build/distr` and 
`java -cp "libs/*:libs/slik2d/*" fw.gui.MainSwingForm`
 for run gui form
