### ISSUE TITLE
Use what visual control for eclipse？

### ISSUE THREAD

**Issue by fmpoffice** [xMlex/l2walker#4]
I use window bulider to open MainSwingForm.java is fail

![image](https://user-images.githubusercontent.com/11001031/79967765-d8dae480-84c1-11ea-9b07-28d7d8109733.png)

Могу я спросить, какое визуальное управление ide должно использоваться

**Comment by xMlex** [comment]
i use intellij idea

**Comment by fmpoffice** [comment]
> i use intellij idea

@xMlex  Thank you very much for your reply

![image](https://user-images.githubusercontent.com/11001031/80191426-4749af00-8648-11ea-8b7e-0fda8ba32be5.png)
awtBotFrame.java
